@extends('layouts.default')
@section('content')
        <section id="content">
          <section class="hbox stretch">
            <aside class="aside-md bg-white b-r" id="subNav">
              <div class="wrapper b-b header">Proforma Manager</div>
              <ul class="nav">
                <li class="b-b b-light"><a href="/invoice"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Pending Proforma</a></li>
                <li class="b-b b-light"><a href="/payments"><i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>Processed Proforma</a></li>
              </ul>
            </aside>
            <aside>
              <section class="vbox">
                <header class="header bg-white b-b clearfix">
                  <div class="row m-t-sm">
                    <div class="col-sm-8 m-b-xs">
                      <a href="#subNav" data-toggle="class:hide" class="btn btn-sm btn-default active"><i class="fa fa-caret-right text fa-lg"></i><i class="fa fa-caret-left text-active fa-lg"></i></a>
                      <a href="#proforma" data-toggle="modal" class="btn btn-sm btn-default"><i class="fa fa-upload"></i> Add New Proforma</a>
                
                   <span class="badge badge-info">Record(s) Found : {{ $bills->total() }} {{ str_plural('Proforma Invoice', $bills->total()) }} </span> 
                    </div>

                  <form action="/find-invoice" method="GET">
                    <div class="col-sm-4 m-b-xs">
                      <div class="input-group">
                        <input type="text" name='search' id='search' class="input-sm form-control" placeholder="Customer, Invoice #, Policy #">
                        <span class="input-group-btn">
                          <button class="btn btn-sm btn-default" type="submit">Go!</button>
                        </span>
                      </div>
                    </div>
                     </form>
                    </div>
                  </div>
                </header>
                <section class="scrollable wrapper w-f">
                  <section class="panel panel-default">
                    <div class="table-responsive">
                      <table class="table table-striped m-b-none text-sm" width="100%">
                        <thead>
                          <tr>
                            
                            
                            <th width="20"></th>
                            <th>Invoice #</th>
                            <th>Customer</th>
                            <th>Date</th>
                            <th>Currency</th>
                            <th>Premium</th>
                            <th>Created On</th>
                            <th>Generated By</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                       @foreach( $bills as $bill )
                          <tr>
                             
                             <td><a href="/print-pro-invoice/{{ $bill->id }}" data-toggle="modal" ><i class="fa fa-print"></i></a></td>
                            <td>{{ $bill->invoice_number }}</td>
                            <td>{{ $bill->account_name }}</td>
                            <td>{{ $bill->created_on }}</td>
                            <td>{{ $bill->currency }}</td>
                            <td>{{ $bill->gross_premium }}</td>
                            <td>{{ $bill->created_on }}</td>
                            <td>{{ $bill->created_by }}</td>
                          </tr>
                         @endforeach 
                        </tbody>
 
                      </table>
                    </div>
                  </section>
                </section>
                <footer class="footer bg-white b-t">
                  <div class="row text-center-xs">
                    <div class="col-md-6 hidden-sm">
                      <p class="text-muted m-t">
                      </p>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right text-center-xs">                
                     
                         {!!$bills->render()!!} 
                        
                    </div>
                  </div>
                </footer>
              </section>
            </aside>
          </section>
          <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
        </section>
@stop



<div class="modal fade" id="proforma" size="600">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Generate Proforma</h4>
        </div>
        <div class="modal-body">
          <p></p>
                      <section class="vbox">
                   
                    <section class="scrollable">
                      <div class="tab-content">
                        <div class="tab-pane active" id="individual">
                           <form  class="bootstrap-modal-form" data-validate="parsley" method="post" action="/do-proforma" class="panel-body wrapper-lg">
                           @include('invoices/quick')
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                      </form>
                        </div>
                  
                  
                        </div>
                      </div>
                    </section>
                  </section>
        </div>
        
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div>





<script src="{{ asset('/event_components/jquery.min.js')}}"></script>


<script type="text/javascript">
$(function () {
  $('#insurance_period').daterangepicker({
    "minDate": moment('2015-06-14 0'),
    "startDate":  moment(),
    "endDate":  moment().add(1, 'years').subtract(1, 'days'),
    "timePicker": true,
    "timePicker24Hour": true,
    "timePickerIncrement": 15,
    "showDropdowns": true,
    "autoApply": true,
    "locale": {
      "format": "DD/MM/YYYY",
      "separator": " - ",
    }
  });
});
</script>


<script type="text/javascript">
$(document).ready(function () {
    
    $('#account_holder').select2();
    $('#business_class').select2();
    $('#account_manager').select2();
    $('#vehicle_model').select2();
    
     
  });
</script>

  

